[colors.bright]
black = "0xFAE8B6"
blue = "0xeba4ac"
cyan = "0x87c095"
green = "0x9cd162"
magenta = "0xd9bcef"
red = "0xff38a2"
white = "0xfff0f5"
yellow = "0xffc85b"

[colors.normal]
black = "0xFAE8B6"
blue = "0xeba4ac"
cyan = "0x87c095"
green = "0x9cd162"
magenta = "0xd9bcef"
red = "0xff38a2"
white = "0xfff0f5"
yellow = "0xffc85b"

[colors.primary]
background = "0x202330"
foreground = "0xfae8b6"

[font]
size = 16

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.offset]
y = 1

[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 1

# OSX
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 120
lines = 36

[window.padding]
x = 25
y = 25

[window.position]
x = 1050
y = 250

[terminal]
